forge 'http://forge.puppetlabs.com'

mod "camptocamp/tomcat"

mod "maestrodev/wget"

mod "puppetlabs/apache"

mod "rtyler/jenkins"

mod "azcender/profiles",
  :git => "https://github.com/azcender/puppet-profiles.git"
mod "azcender/roles",
  :git => "https://github.com/azcender/puppet-roles.git"
